- src/app/v1/mobile-auth/route.ts
By default `response_mode = fragment`, this reflects such handling.
> fix: default response_mode in native sign in

- src/app/authorize/route.ts
redirects users to the World App download page (with a subsequent redirect to the correct app store) if they visit id.worldcoin.org/authorize from a mobile device
opening id.worldcoin.org/authorize on mobile should ALWAYS open the app directly and completely avoid the flow using the bridge, so if the app is not installed it is safe to direct to the download page
caveat: some android tablets may be detected as mobile devices by the user-agent header. this can be bypassed with the "Request Desktop Site" feature of any mobile web browser.
> feat: redirect authorize to download if on mobile

- src/api-helpers/validation.ts
Handles `null` or `""` as values for `/v1/mobile-auth` inputs properly by casting them to undefined and applying the default value. (Hopefully) fixes an issue present with Android native World ID sign-in.
My suspicion:
- Android app sends request to `/v1/mobile-auth` with `response_mode` as `null`
- Yup default is not applied, as they only apply when value is `undefined`
- Test statement passes, as it returns true when `!value`
- `/v1/mobile-auth/route.ts` checks `parsedParams.response_mode === OIDCResponseMode.Query`, which is false, as `response_mode` is `null`, so it uses fragment response mode in response to World App
> fix: handle null or empty string response mode

- src/api-helpers/utils.ts
log response_type and response_mode before and after yup validation, temporary for debugging
> debug: response_type and response_mode logging

- Dockerfile
- src/api-helpers/utils.ts
- src/api-helpers/validation.ts
allows undefined, null, and "" values for response_mode to be properly handled and use the default based on the response_type
the earlier bug was an issue in dd-trace v5.11.0, and when we rolled back, we somehow ended up with v5.12.0 (containing the fix) getting released in the 4 minutes between the staging and prod deploys, so staging still didn't work, but prod did
wack
> fix: handle empty response mode

- src/lib/authenticate.ts
the `scope` parameter is usually separated with a URI-encoded space (`%20`), but some implementations use `+` instead. World App on iOS will submit to the `/v1/mobile-auth` endpoint using `+` as a separator, but the Developer Portal expects `%20`, so this PR transforms the scope to replace `+` with `%20` before passing to the dev portal.
> fix: transform plus to space in scope

- Dockerfile
I think env vars in const.ts are not defined when it's getting compiled. This is resulting in well known file for staging to be pointing to prod
Also updating docker file to pull node from ecs to avoid rate limit
> [Fix] Add build args

- src/app/authenticate/route.ts
Adds sign-in params to error page when proof verification fails so "Try Again" works.
> fix: pass params to error page so retry works

- src/lib/authenticate.ts
enforces the following limitations on the `state` parameter:
- contains only alphanumeric, comma, period, underscore, and hyphen characters
- 256 characters or less
> feat: set state parameter limitations

- src/app/authorize-web/route.ts
- src/app/authorize/route.ts
Adds the `/authorize-web` endpoint, which allows third-party applications using Sign In with World ID to choose the bridge flow as opposed to the mobile-native flow.
Applications that wish to always use the bridge flow can simply replace `id.worldcoin.org/authorize?client_id=app_...` with <code>id.worldcoin.org/**authorize-web**?client_id=app_...</code>.
This PR is prompted by a specific integration of Sign In with World ID which uses ICP's Internet Identity, which by design requires that the `redirect_uri` be visited from the same tab that initiated the sign in process. The mobile-native flow will always open the `redirect_uri` in a new tab due to iOS/Android limitations, and this method is intended as a workaround.
> feat: authorize-web endpoint

- src/app/authorize-web/route.ts
was redirecting to AWS internal URL
> fix: use public url for authorize-web redirect

- src/app/login/ClientPage.tsx
- src/components/IDKitBridge.tsx
Mobile platforms will not treat an automatic new tab open as a deeplink, it must be prompted by a user action. This PR removes the auto-open functionality and adjusts copy accordingly, as well as a few small visual fixes on mobile platforms.
> fix: don't auto-open world app on mobile

- src/app/authorize-web/route.ts
- src/app/authorize/route.ts
Refactors the `/authorize-web` endpoint to simply re-export `/authorize`. This means that a redirect to `/authorize` is bypassed when using `/authorize-web`, preventing opening World App via deeplink.
> feat: authorize-web refactor

- src/app/authorize/route.ts
Small fix to prevent redirecting to app store on mobile from `/authorize-web` endpoint.
> fix: don't redirect to app store on /authorize-web

- src/app/login/ClientPage.tsx
- src/components/IDKitBridge.tsx
If the screen is too small the QR code is gone. Fix this by user agents instead
if name is too long it was extending out of the modal
> ui bug fixes

- src/app/login/ClientPage.tsx
- src/components/IDKitBridge.tsx
I remove the manual button we had before since I believe all situations we should account for are covered by the new button. This will improve the visual flow when we have to trigger a manual sign in and cannot automatically open the universal link -> redirect
> Improve Mobile Sign In

- src/app/authenticate/route.ts
- src/lib/authenticate.ts
Nonce should not be required for `code` or `code token` response types
> fix: don't require nonce for auth code flow

- src/app/authorize/route.ts
- src/lib/authenticate.ts
developer portal expects a signal value to be provided, and throws an error when one is not provided. this updates yup validation to cast undefined and null nonce values to `""` using `.ensure()`, which will fail validation when nonce is required, but otherwise will provide a value to the developer portal to avoid errors
> fix: default to "" nonce when not required

- src/lib/authenticate.ts
Allows `state` param to include all valid Base64 characters, since Auth0 SPA SDK uses Base64-encoded value for the state by default.
> feat: allow base64 chars

- src/app/login/page.tsx
Currently Next caches the fetched mini app data and never refetches it.
> fix: Disable fetch caching
