worldcoin/world-id-sign-in

- components/IDKitBridge.tsx
- components/icons.tsx
- pages/api/authenticate.ts
- pages/api/authorize.ts
- pages/error.tsx
- pages/login.tsx
- Adds early redirect URI validation
- Fixes bugs with `undefined` optional params.
> feat: redirect URI validation

- src/app/authorize/route.ts
This was causing unhandled 500 errors.
> fix: better error handling for validate responses

- next.config.js
Pair PR to https://github.com/worldcoin/developer-portal/pull/424
> remove register endpoint

- public/.well-known/apple-app-site-association
- src/lib/authenticate.ts
For Sign in with World ID within native apps.
> feat: update apple association for /authorize endpoint

- src/api-helpers/errors.ts
- src/api-helpers/utils.ts
- src/app/authenticate/route.ts
- src/app/authorize/route.ts
- src/lib/utils.ts
- src/middleware.ts
- src/styles/globals.css
- tests/e2e/oidc-route.test.ts
- tests/unit/authenticate.test.ts
- tests/unit/authorize.test.ts
@pdtfh  Not sure where exactly we should use it. I've added to font-src, style-src and img-src
> feat: add assets url to the scp settings

- Dockerfile
- next.config.js
- Adds source maps for server side debugging.
- Optimizes Docker build by fetching server dependencies in a separate layer.
> add source maps & optimize Docker build

- next.config.js
- src/app/.well-known/openid-configuration/route.ts
- src/app/authorize/route.ts
- src/app/oidc-route/route.ts
- src/consts.ts
- src/types.ts
- tests/e2e/oidc-route.test.ts
- tests/e2e/openid-configuration.test.ts
PR moves `/.well-known/openid-configuration` to this repo instead of proxying to Developer Portal.
> feat: move openid-configuration to repo

- .env.sample
- package.json
- pnpm-lock.yaml
- src/app/login/ClientPage.tsx
- src/consts.ts
- src/middleware.ts
uses env vars to set URL's for staging environment in all responses, and allows using staging dev portal with staging sign-in
also bumps IDKit to v1.1.4
merge in tandem with https://github.com/worldcoin/world-id-deploy/pull/51
> feat: use env vars

- src/api-helpers/validation.ts
Reverts worldcoin/world-id-sign-in#65
> Revert "fix: handle null or empty string response mode"

- Dockerfile
> revert-changes

- src/consts.ts
Trying to set dev values to staging
> [fix] update-const

- Dockerfile
> docker build args

- src/app/authenticate/route.ts
Sanitizes form-post HTML attributes to alphanumeric characters, `.`, `_`, and `-`.
Completes DEV-1040
> feat: sanitize form-post html attr

- .github/workflows/ci.yml
- Dockerfile
- pnpm-lock.yaml
Fixes the deploy and improves the docker file as well
> improve docker file and ci

- src/app/login/ClientPage.tsx
- src/components/IDKitBridge.tsx
Navigator is undefined sometimes and throwing errors in datadog
> fix navigator undefined error

- package.json
- pnpm-lock.yaml
- src/app/login/ClientPage.tsx
- src/app/login/IDKitQR.tsx
- src/app/login/page.tsx
- src/components/IDKitBridge.tsx
- src/lib/utils.ts
Fix mobile ui. Not nots :(
Also move to use server side function instead for precheck
Also upgrade next
> fix mobile ui

- package.json
- pnpm-lock.yaml
> Upgrade Next

- src/app/authorize/route.ts
- src/app/login/page.tsx
- src/global.d.ts
> Mini App Sign in Support

- src/app/login/MiniAppWrapper.tsx
- src/app/login/page.tsx
> Fix Sign In

- src/app/login/page.tsx
remove old sign in breaking build
> remove old sign in

- src/app/login/MiniAppWrapper.tsx
> Fix Redirects

- src/app/login/MiniAppWrapper.tsx
> fix window undefined

- Dockerfile
removed corepack to fix corepack error
> fix: removed corepack from dockerfile

- package.json
- pnpm-lock.yaml
bump idkit here since it allows us to add new verification levels we support
> Bump IDKit

- package.json
- pnpm-lock.yaml
> bump next version

- src/lib/authenticate.ts
state parameter was too short many places have 500+ characters
> bump state param length

- src/app/.well-known/openid-configuration/route.ts
- src/app/authorize/route.ts
- src/app/oidc-route/route.ts
Fixes check of the content-type header in the request body processing.
Adds RS256 to the supported algorithms for id_token signing.
> fix: Fix request body processing

- .github/workflows/ci.yml
- public/robots.txt
- src/app/layout.tsx
- src/app/oidc-route/route.ts
- Disable SEO indexing
- Bump CI ubuntu version https://github.com/actions/runner-images/issues/11101
> Disable SEO indexing, Bump Ubuntu CI version

- package.json
- pnpm-lock.yaml
- src/app/login/IDKitQR.tsx
- src/lib/utils.ts
Ipad currently has an issue where the QR code doesn't load. This is because of it being considered a mobile flow but it is above the breakpoints.
Given IPads could be both holding the World App and just used as an external computer we will handle both cases to let you deep link directly with a button and see the QR code
Old (IPad):
NEW (IPad):
> Fix Ipad Visual Issues
